# Basic site configuration
# ------------------------
site_name: 'PI-AVG: Computational Genomics Algorithms' # Name of the site
site_url: https://fulopjoz.github.io/pi-avg # Replace with your actual site URL
site_dir: site # Directory where the built site files will be placed
docs_dir: docs # Directory containing your documentation source files

# Repository configuration
# ------------------------
repo_url: https://github.com/fulopjoz/pi-avg # URL to your source code repository
repo_name: 'PI-AVG Computational Genomics Algorithms' # Name of the source code repository
edit_uri: blob/main/docs # URI to the source file in the repository, used for the "Edit this page" links

# Theme configuration
# -------------------
theme:
  name: material # Name of the theme
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.action.view # Enables the 'view' action button
    - content.code.copy # Adds copy button besides code blocks
  font:
    code: JetBrains Mono # Change code block font to JetBrains mono
  icon:
    logo: material/dna
    repo: fontawesome/brands/github # Icon for the repository link
    view: material/eye # Icon for the 'view' action button
  palette:
    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

# Markdown extensions
# -------------------
markdown_extensions:
  - admonition # Support for admonitions (notes, warnings, etc.)
  - attr_list # Allows adding attributes to HTML tags
  - def_list
  - footnotes # Enables support for footnotes
  - meta
  - toc:
      permalink: true # Enables permalinks for headings
  - pymdownx.arithmatex:
      generic: true # Support for LaTeX math
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details # Support for details/summary tags
  - pymdownx.emoji # Emoji support
  - pymdownx.highlight # Syntax highlighting for code blocks
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink # Automatic linking for URLs and email addresses
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences # Extra fences for code blocks
  - pymdownx.tabbed:
      alternate_style: true # Support for block tabs in html page
  - pymdownx.tasklist # Support for task lists
  - pymdownx.tilde

# Extra resources
# ---------------
extra_css:
  - assets/css/custom.css # Additional CSS styles

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

# Plugins
# -------
plugins:
  - search # Adds a search bar to the site
  - bibtex:
      bib_file: "docs/references.bib"
  - roamlinks # Support for wikilinks similar to Roam Research and Obsidian
  - markdown-exec # Support for execution of code blocks

# Navigation structure
nav:
  - Home: index.md
  - Sequence Alignment:
    - Overview: alignments/index.md
    - Basic Concepts: alignments/basic.md
    - Edit Distance: alignments/edit_distance.md
    - Global & Local Alignment: alignments/global_local.md
    - Affine Gap Penalties: alignments/affine_gap.md
  - Algorithms:
    - Overview: algorithms/index.md
  - Data Structures:
    - Overview: data_structures/index.md
  - Case Studies:
    - Overview: case_studies/index.md
  - Code Examples:
    - Overview: code_examples/index.md
